### ISSUE TITLE
How about to replace tendermint with gosig?

### ISSUE THREAD

**Issue by diyism** [davebryson/bftdb#3]
I know that gosig protocol is a scalable BFT.
How do you think about replacing tendermint in bftdb with the gosig protocol?

Ref:
https://www.cs.toronto.edu/~fanl/papers/gosig-socc20.pdf
https://github.com/gauravagarwaltal/consensus_gosig

**Comment by davebryson** [comment]
bftdb is primarily intended as a demonstration of what's possible.  For now Tendermint is more than sufficient.
